from .index import IndexView
from .search import SearchView
from .categories import CategoriesView
from .leaderboards import LeaderboardsView
from .dashboard import DashboardView
from .settings import SettingsView
from .owned_games import OwnedGamesView
from .orders import OrdersView
from .managed_games import ManagedGamesView
from .sales import SalesView
from .new_game import NewGameView
from .game import GameView
from .game_edit import GameEditView
from .login import LoginView
from .logout import logout_view
from .cart import CartView
